<?php
namespace Jarzon\Input;

use Jarzon\TextBasedInput;

class EmailInput extends TextBasedInput
{
    public function __construct(string $name)
    {
        parent::__construct($name);
        $this->setAttribute('type', 'email');
    }

    public function validation($value = null, $update = false)
    {
        return parent::validation($value, $update); // TODO: Change the autogenerated stub
    }
}